version: '3'

services: 
  mantisbt:
    container_name: mantisbt
    image: rickymbru/mantisbt:2.25.4
    build:
      context: ./docker/mantisbt
      dockerfile: Dockerfile    
    ports:
    - "8989:80"
    volumes:
        - ./html/config:/var/www/html/config
        - ./html/custom:/var/www/html/custom
        - ./html/images:/var/www/html/images
        - ./html/core:/var/www/html/core        
        - ./html/lang:/var/www/html/lang
        - ./html/config_defaults_inc.php:/var/www/html/config_defaults_inc.php
        - ./html/bug_update_page.php:/var/www/html/bug_update_page.php
        - ./html/bug_view_page.php:/var/www/html/bug_view_page.php
        - ./html/bug_view_inc.php:/var/www/html/bug_view_inc.php
    restart: always

  mysql:
    container_name: mysql
    image: rickymbru/mariadb:latest
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    ports:
    - "3306:3306"      
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bugtracker
      MYSQL_USER: mantisbt
      MYSQL_PASSWORD: mantisbt
    volumes:
    - ./mysql:/var/lib/mysql
    restart: always