version: '3'

services: 
  mantisbt:
    container_name: mantisbt
    image: rickymbru/mantisbt:2.25.4
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
    - "8989:80"
    volumes:
        #- ./config:/var/www/html/config
        - ./custom:/var/www/html/custom
    restart: always

  mysql:
    container_name: mysql
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bugtracker
      MYSQL_USER: mantisbt
      MYSQL_PASSWORD: mantisbt
    volumes:
    - ./mysql:/var/lib/mysql
    restart: always