version: '3'

services: 
  mantisbt:
    container_name: mantisbt
    image: rickymbru/mantisbt:2.25.4
    build:
      context: ./docker/mantisbt
      dockerfile: Dockerfile    
    ports:
    - "8989:80"
    volumes:
        - ./mantisbt:/var/www/html/
    restart: always

  mysql:
    container_name: mysql
    image: rickymbru/mariadb:latest
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    ports:
    - "3306:3306"      
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bugtracker
      MYSQL_USER: mantisbt
      MYSQL_PASSWORD: mantisbt
    volumes:
    - ./mysql:/var/lib/mysql
    restart: always